Update main.yml
Update per MedAziz11

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,17 +59,20 @@ jobs:
         run: |
           REPO=${{ env.DOCKERHUB_REPO }}
           IMAGE=${{ env.DOCKERHUB_IMAGE }}
-          
-          if [ "${{ github.event_name }}" == "pull_request" ]; then
-            BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | sed 's/\//-/g')
+
+          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
+            TAGS="${REPO}/${IMAGE}:latest"
+          elif [[ $GITHUB_REF == "refs/heads/develop" ]]; then
+            TAGS="${REPO}/${IMAGE}:dev"
+          elif [[ $GITHUB_REF == refs/tags/* ]]; then
+            VERSION=$(echo ${GITHUB_REF#refs/tags/v} | sed 's/\//-/g')
+            TAGS="${REPO}/${IMAGE}:v${VERSION},${REPO}/${IMAGE}:latest"
           else
-            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
+            echo "Error: Unexpected branch or tag"
+            exit 1
           fi
 
-          PLATFORM_TAG=$(echo "${{ matrix.platform }}" | sed 's/\//-/g')
-          TAGS="${REPO}/${IMAGE}:${BRANCH_NAME},${REPO}/${IMAGE}:${BRANCH_NAME}-${PLATFORM_TAG}"
           echo "::set-output name=tags::${TAGS}"
-
 
       # Build, test, and push the Docker image
       - name: Build, Test, and Push Docker image
